const roleRoutes: Record<string, (string | RegExp)[]> = {
  USERS: [
    "/page/trending",
    /^\/page\/detail_user\/[\w-]+$/, // Chấp nhận chữ cái, số và dấu -
    "/page/music-favorite",
    "/page/my-music",
    "/page/my-video",
    "/page/following",
    "/page/profile",
    "/page/search-user-video",
    "/page/videohistory",
    /^\/page\/share\/[\w-]+$/,
    /^\/page\/shareMusic\/[\w-]+$/,
    /^\/page\/music\/[\w-]+$/,
    /^\/page\/store\/[\w-]+$/,
    "/page/store/manage-product",
    /^\/page\/store\/manage-product\/[\w-]+$/,
    /^\/page\/store\/manage-order\/[\w-]+$/,
    /^\/page\/store\/manage-payment\/[\w-]+$/,
    "/page/playlist",
    "/page/rankings",
    /^\/page\/rankings\/music\/[\w-]+$/,
    /^\/page\/rankings\/video\/[\w-]+$/,
    /^\/page\/rankings\/creator\/[\w-]+$/,
    "/page/music",
    "/page/detail_cart",
    "/personal/musichistory",
    "/page/shop/order",
    "/page/order-confirmation",
    "/page/purchasehistory",
    "/page/shop",
    "/page/shop/recommend",
    "/page/shop/cart",
    "/page/shop/address",
    "/page/shop/check-out",
    "/page/shop/check-out/success",
    "/page/shop/check-out/fail",
    "/page/store",
    /^\/page\/shop\/product\/[\w-]+$/,
    /^\/page\/shop\/rating\/[\w-]+$/,
    /^\/page\/shop\/store\/[\w-]+$/,
    "/page/karaoke",
    "/page/profile/edit",
  ],
  GUEST: [
    "/page/trending",
    "/page/rankings",
    /^\/page\/detail_user\/[\w-]+$/,
    "/page/search-user-video",
    /^\/page\/rankings\/music\/[\w-]+$/,
    /^\/page\/rankings\/video\/[\w-]+$/,
    /^\/page\/rankings\/creator\/[\w-]+$/,
    "/auth/login",
    "/auth/forgotpassword",
    "/auth/register",
    "/page/music",
    "/page/karaoke",
    /^\/verify\/[\w-]+$/,
    /^\/page\/share\/[\w-]+$/,
    /^\/page\/music\/[\w-]+$/,
    /^\/page\/shareMusic\/[\w-]+$/,
    /^\/page\/detail_user\/[\w-]+$/,
    /^\/page\/store\/[\w-]+$/,
    "/page/shop",
    /^\/page\/product-detail\/[\w-]+$/,
    "/page/trending-new-ui",
  ],
  ADMIN: [
    "/dashboard/user",
    "/dashboard/report",
    "/dashboard/short-video",
    "/dashboard/report/report-video",
    "/dashboard/report/report-music",
    "/dashboard/music",
    "/dashboard/algorithm",
    /^\/page\/detail_user\/[\w-]+$/,
    "/dashboard/ticked",
    "/dashboard/statistic/users",
    "/dashboard/statistic/videos",
    "/dashboard/statistic/musics",
  ],
};

const defaultRoutes: Record<string, string> = {
  USERS: "/page/trending",
  GUEST: "/page/trending",
  ADMIN: "/dashboard/user",
};

export { roleRoutes, defaultRoutes };
